version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - 5690:5690
    volumes:
      - .:/app
      - ./db/:/cats_notes
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
