name: DoubleEnc
description: |

  Существует такая криптосистема(?) - ISD. Описана она в работе https://arxiv.org/abs/1907.12754 А ещё там двойное зашифрование флага. Вы знаете, что надо делать дальше...`

author: '@bork_dog'
category: crypto
flag: ptctf{0364961FE7851C7C495AD3EDAAF4B541}
warmup: false
server_port: null
