name: Салат
description: |
  Crypto - сокращенное название категории Cryptography (Криптография). 
  
  Это раздел, посвященный математическим методам защиты информации - и в этой категории надо играть роль криптоаналитика, задачи этой категории могут включать взлом слабо реализованных криптографических систем, выявление уязвимостей в алгоритмах шифрования или понимание и использование слабых мест криптографии. 
  
  На сложных CTF в этой категории сплошная алгебра, мы же предлагаем вам начать с примитивных исторических шифров. Данная категория будет вам интересна, если вы обожаете математику и ее применение в защите информации. 

  ---
  
  Классика как кулинарного мира, так и начинающих криптографов.

author: "@greg0r0"
category: crypto
flag: ptctf{d0nt_f0rg3t_t0_4dd_th3_cr0ut0ns}
warmup: true
server_port: null
